"""added approved field

Revision ID: 3ff3e53fce87
Revises: f4278e665f74
Create Date: 2023-10-04 07:08:38.485590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff3e53fce87'
down_revision: Union[str, None] = 'f4278e665f74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_study', sa.Column('approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enrollment_study', 'approved')
    # ### end Alembic commands ###
