"""change fields enrollment study

Revision ID: f4278e665f74
Revises: fa252430d5ee
Create Date: 2023-10-04 06:55:31.263289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4278e665f74'
down_revision: Union[str, None] = 'fa252430d5ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_study', sa.Column('career_id', sa.Integer(), nullable=False))
    op.add_column('enrollment_study', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.drop_constraint('enrollment_study_carrera_id_fkey', 'enrollment_study', type_='foreignkey')
    op.drop_constraint('enrollment_study_materia_id_fkey', 'enrollment_study', type_='foreignkey')
    op.create_foreign_key(None, 'enrollment_study', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(None, 'enrollment_study', 'career', ['career_id'], ['id'])
    op.drop_column('enrollment_study', 'materia_id')
    op.drop_column('enrollment_study', 'carrera_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrollment_study', sa.Column('carrera_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('enrollment_study', sa.Column('materia_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'enrollment_study', type_='foreignkey')
    op.drop_constraint(None, 'enrollment_study', type_='foreignkey')
    op.create_foreign_key('enrollment_study_materia_id_fkey', 'enrollment_study', 'subjects', ['materia_id'], ['id'])
    op.create_foreign_key('enrollment_study_carrera_id_fkey', 'enrollment_study', 'career', ['carrera_id'], ['id'])
    op.drop_column('enrollment_study', 'subject_id')
    op.drop_column('enrollment_study', 'career_id')
    # ### end Alembic commands ###
